name: test-env

on:
  workflow_dispatch:
    inputs:
     runner_name:
       type: choice
       description: Select runners group
       options: 
       - vmss-caas-gitrunner-weu-dev
       - vmss-caas-gitrunner-weu-testqa

jobs:
  build:

#     runs-on: ${{ github.event.inputs.runner_name }}
#     environment: ${{ environment_name }}
    if: ${{ github.ref_name == 'development' }}
        with:
            environment_name: 'DEV'
    if: ${{ github.ref_name == 'testqa' }}
        with:
            environment_name: 'TEST'
    
    steps:
    - uses: actions/checkout@v2
        
    - name: Echo 
      run: |
      echo "echo!!!!"
      echo ${{ environment_name }}

    
