name: test-env

on:
#   push:
#     branches: [ "Development" ]
#   pull_request:
#     branches: [ "Development" ]

  workflow_dispatch:
    inputs:
     runner_name:
       type: choice
       description: Select runners group
       options: 
       - vmss-caas-gitrunner-weu-dev
       - vmss-caas-gitrunner-weu-testqa

jobs:
  build:
    runs-on: ubuntu-latest
    #environment: ${{ environment_name }}

    steps:
      - uses: actions/checkout@v3

      - name: Echo
        run: |
            echo "nc -vz sql-pcl-dev-weu-001.database.windows.net 1433"
            nc -vz -w 5 sql-pcl-dev-weu-001.database.windows.net 1433
            echo "nc -vz sql-pcl-testqa-weu-001.database.windows.net 1433"
            nc -vz -w 5 sql-pcl-testqa-weu-001.database.windows.net 1433
            echo "runner:${{ github.event.inputs.runner_name }}"
            echo "branch:${{ github.ref_name }}"
            echo "env:${{ fromJSON('{"Development":"DEV","testqa":"TEST"}')[github.ref_name] }}"
        continue-on-error: true
            
          
          

    
