name: test-env

on:
  workflow_dispatch:
    inputs:
     runner_name:
       type: choice
       description: Select runners group
       options: 
       - vmss-caas-gitrunner-weu-dev
       - vmss-caas-gitrunner-weu-testqa

  jobs:
    build:
      name: "dddd"
      environment: ${{ environment_name }}
   
    steps:
     - uses: actions/checkout@v2
         
     - name: Echo 
       run: |
         echo "echo"
         echo ${{ fromJSON('{"development":"DEV","testqa":"TEST"}')[github.ref_name] }}

    
